Repository konveyor/tackle-container-advisor, pull requests merged in 2022-12, with the labels that each got.

#179 Updated performance benchmarking scripts
  config/test.ini
  test/performance/run_payload.py
Labels: documentation

#180 json compatible standardize output
  service/clustering.py
  service/infer_tech.py
  service/planning.py
  service/standardization.py
  service/utils.py
  setup.sh
  test/unit/test_assessment.py
  test/unit/test_clustering.py
  test/unit/test_planning.py
  test/unit/test_standardization.py
Labels: kind/feature, size/S, feature

#183 Payload performance bug fix
  docs/running.md
  service/standardization.py
  test/performance/run_payload.py
Labels: kind/bug
