Repository konveyor/tackle-container-advisor, pull requests merged in 2022-07, with the labels that each got.

#131 Single tech_summary input for entity standardization, renamed API endpoints
  service/assessment.py
  service/clustering.py
  service/functions.py
  service/infer_tech.py
  service/requirements.txt
  service/routes.py
  service/standardization.py
  test/unit/test_assessment.py
  test/unit/test_standardization.py
Labels: Code_Refactoring, api-review, size/M, enhancement

#132 Add siamese
  benchmarks/run_models.py
  config/deploy/siamese.ini
  config/tca/siamese.ini
  entity_standardizer/entity_standardizer/__init__.py
  entity_standardizer/entity_standardizer/siamese/__init__.py
  entity_standardizer/entity_standardizer/siamese/data.py
  entity_standardizer/entity_standardizer/siamese/loss.py
  entity_standardizer/entity_standardizer/siamese/main.py
  entity_standardizer/entity_standardizer/siamese/model.py
  entity_standardizer/requirements.txt
  entity_standardizer/setup.py
  setup.sh
Labels: Code_Refactoring, deployment, size/M, feature

#134 sync fork
  kg_utils/kg_utils.py
  service/planning.py
  test/unit/test_clustering.py
  test/unit/test_planning.py
  test/unit/test_sim_applier.py
  test/unit/test_utils.py
Labels: Code_Refactoring, deployment, size/M, feature

#137 KG and Unit tests changes
  db/1.0.4.sql
  service/clustering.py
  service/functions.py
  service/planning.py
  service/routes.py
  test/unit/test_clustering.py
  test/unit/test_standardization.py
Labels: KG_Refactoring, deployment, kind/cleanup, size/M, fix
